# FROM node:18

# WORKDIR /app
# COPY package*.json ./
# RUN npm install

# COPY . .

# CMD ["node", "server.js"]




# -------- STAGE 1: Build --------
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# -------- STAGE 2: Production --------
FROM node:18-slim

WORKDIR /app

# Copy only necessary files from builder
COPY --from=builder /app /app

# Remove dev dependencies (optional but good)
RUN npm prune --production

CMD ["node", "server.js"]